site_name: Graficas

docs_dir: 'md'

site_dir: 'docs'

theme: 
  name: material
  favicon: './img/favicon.ico'

nav:
  - Index: index.md
  - Software: software.md
  - Hardware:
    - Subseccion 1: hardware/gpu.md
    - Subseccion 2: hardware/transformacion.md
  - Aplicaciones:
    - Subseccion 2.1: aplicaciones/uso.md
